/*an entity in programming is any objest designed to be saved/persisted 
somewhere
DO NOT FORGET to EXPORT anything I want to use in another file

*/

import Account from "./account";

export default interface Client{
   
    id: string //customer unique identifier generated by uuid
    fname: string //customer first name
    lname: string //customer last name
    accounts?: Account[]; //provides Balance and Account type in order
    
    }